// Contingut dels documents legals de FindYourBet (FYB).
// IMPORTANT: Omplir les dades ⟦…⟧ amb la informació legal real abans de publicar.
// Revisar amb advocat especialitzat en dret digital / dret del joc.

export const COMPANY = {
  brand: 'FindYourBet',
  legalName: '⟦RAZÓN SOCIAL / NOMBRE Y APELLIDOS DEL TITULAR⟧',
  taxId: '⟦NIF / CIF⟧',
  address: '⟦DIRECCIÓN FISCAL COMPLETA⟧',
  registry: '⟦DATOS REGISTRALES (si es sociedad) — Registro Mercantil, tomo, folio, hoja⟧',
  email: 'fyourbet@gmail.com',
  domain: 'fyourbet.com',
}

export const LAST_UPDATED = { es: '7 de julio de 2026', en: 'July 7, 2026', fr: '7 juillet 2026' }

export const LEGAL_ORDER = ['aviso-legal', 'terminos', 'privacidad', 'cookies', 'juego-responsable']

// ─── ESPAÑOL ─────────────────────────────────────────────────────────────────
const LEGAL_DOCS_ES = {
  'aviso-legal': {
    slug: 'aviso-legal', title: 'Aviso Legal', short: 'Aviso Legal',
    desc: 'Datos identificativos del titular y condiciones generales de uso del sitio web.',
    blocks: [
      { h3: '1. Datos identificativos' },
      { p: `En cumplimiento del artículo 10 de la LSSI-CE, el titular del presente sitio web es:` },
      { ul: [`Titular: ${COMPANY.legalName}`, `NIF/CIF: ${COMPANY.taxId}`, `Domicilio: ${COMPANY.address}`, `Datos registrales: ${COMPANY.registry}`, `Contacto: ${COMPANY.email}`, `Sitio web: ${COMPANY.domain}`] },
      { h3: '2. Objeto y naturaleza del servicio' },
      { p: `FindYourBet (FYB) es una red social y marketplace de información y pronósticos deportivos. No es un operador de juego. No se realizan apuestas ni se abonan premios dentro de la Plataforma.` },
      { h3: '3. Condiciones de acceso' },
      { p: `El acceso es gratuito. Algunos contenidos premium pueden requerir pago. El uso está reservado a mayores de 18 años.` },
      { h3: '4. Propiedad intelectual' },
      { p: `La marca, diseño y código de FindYourBet están protegidos por la normativa de propiedad intelectual e industrial. El contenido de los usuarios es responsabilidad de sus autores.` },
      { h3: '5. Exención de responsabilidad' },
      { p: `Los pronósticos son opiniones personales y no constituyen asesoramiento financiero. FYB no garantiza la disponibilidad ininterrumpida del servicio.` },
      { h3: '6. Legislación aplicable' },
      { p: `Estas condiciones se rigen por la legislación española. Para disputas, serán competentes los juzgados determinados por la normativa de consumidores y usuarios.` },
    ],
  },
  'terminos': {
    slug: 'terminos', title: 'Términos y Condiciones', short: 'Términos y Condiciones',
    desc: 'Condiciones que regulan el uso de FindYourBet para usuarios y tipsters.',
    blocks: [
      { p: `Estos Términos regulan el acceso y uso de FindYourBet (FYB). Al registrarte o usar la Plataforma, los aceptas íntegramente.` },
      { h3: '1. Descripción del servicio' },
      { p: `FYB es una red social y marketplace de pronósticos deportivos. No es un operador de juego. No se realizan apuestas ni se gestionan fondos de juego.` },
      { h3: '2. Requisitos de acceso' },
      { ul: [`Mayor de 18 años.`, `Jurisdicción donde el servicio sea legal.`, `Información veraz en el registro.`, `Responsabilidad sobre las credenciales de acceso.`] },
      { h3: '3. Cuentas de usuario' },
      { p: `FYB puede suspender cuentas que incumplan estos Términos, suplanten identidades o publiquen contenido ilícito.` },
      { h3: '4. Tipsters y contenido' },
      { p: `Los tipsters son responsables de su contenido y declaran que los pronósticos son solo informativos, sin garantía de resultado. Queda prohibido publicar enlaces de afiliación a casas de apuestas.` },
      { h3: '5. Pagos y comisiones' },
      { p: `Los pagos se procesan mediante Stripe Connect. FYB retiene una comisión de entre el 15% y el 20%. Los precios se muestran antes de cada compra.` },
      { h3: 'Canales VIP y suscripciones' },
      { p: `Las suscripciones VIP no se renuevan automáticamente. El acceso expira al finalizar el periodo contratado. El tipster es responsable del contenido de su canal.` },
      { h3: '6. Política de reembolsos' },
      { p: `Por la naturaleza digital del contenido y el acceso inmediato (art. 103 RDL 1/2007), no aplica el derecho de desistimiento. FYB puede estudiar reembolsos por error de cobro o incidencias técnicas graves. Contacto: ${COMPANY.email}` },
      { h3: '7. Ausencia de garantías' },
      { p: `Los pronósticos son opiniones. Ningún historial, yield o estadística garantiza resultados futuros. El rendimiento pasado no indica el rendimiento futuro.` },
      { h3: '8. Conducta prohibida' },
      { ul: [`Actividades ilícitas o fraudulentas.`, `Acosar, amenazar o suplantar a otros usuarios.`, `Manipular estadísticas o historiales.`, `Crear cuentas falsas.`, `Promocionar casas de apuestas o incluir enlaces de afiliación.`] },
      { h3: '9. Modificaciones' },
      { p: `FYB puede modificar estos Términos. Los cambios sustanciales se comunicarán en la Plataforma. El uso continuado implica aceptación.` },
      { h3: '10. Contacto' },
      { p: `Para consultas: ${COMPANY.email}` },
    ],
  },
  'privacidad': {
    slug: 'privacidad', title: 'Política de Privacidad', short: 'Privacidad',
    desc: 'Cómo tratamos tus datos personales conforme al RGPD y la LOPDGDD.',
    blocks: [
      { p: `En FindYourBet protegemos tus datos conforme al RGPD (UE) 2016/679 y la LOPDGDD (LO 3/2018).` },
      { h3: '1. Responsable del tratamiento' },
      { ul: [`Responsable: ${COMPANY.legalName}`, `NIF/CIF: ${COMPANY.taxId}`, `Domicilio: ${COMPANY.address}`, `Contacto: ${COMPANY.email}`] },
      { h3: '2. Datos que tratamos' },
      { ul: [`Registro: nombre, usuario, email, fecha de nacimiento, nacionalidad.`, `Perfil: bio, avatar y contenido que publiques.`, `Actividad: picks, mensajes, follows, likes.`, `Pago: gestionado por Stripe (FYB no almacena datos de tarjeta).`, `Técnicos: IP, dispositivo, datos de uso.`] },
      { h3: '3. Finalidades y base jurídica' },
      { ul: [`Prestación del servicio — ejecución del contrato.`, `Procesar pagos — ejecución del contrato.`, `Comunicaciones transaccionales — ejecución del contrato.`, `Seguridad y prevención de fraude — interés legítimo.`, `Obligaciones legales — obligación legal.`] },
      { h3: '4. Destinatarios' },
      { ul: [`Supabase — base de datos y autenticación.`, `Google — inicio de sesión OAuth.`, `Stripe — procesamiento de pagos.`, `Resend — correos transaccionales.`, `Vercel — alojamiento web.`] },
      { p: `No vendemos tus datos personales a terceros.` },
      { h3: '5. Transferencias internacionales' },
      { p: `Algunos proveedores pueden tratar datos fuera del EEE, amparados en cláusulas contractuales tipo de la Comisión Europea.` },
      { h3: '6. Conservación' },
      { p: `Conservamos tus datos mientras tu cuenta esté activa. Al eliminarla, suprimiremos tus datos, salvo los que debamos conservar por ley.` },
      { h3: '7. Tus derechos' },
      { p: `Puedes ejercer los derechos de acceso, rectificación, supresión, oposición, limitación y portabilidad escribiendo a ${COMPANY.email}. También puedes reclamar ante la AEPD (www.aepd.es).` },
      { h3: '8. Seguridad' },
      { p: `Aplicamos control de acceso por filas (RLS), cifrado en tránsito y minimización de datos.` },
      { h3: '9. Menores de edad' },
      { p: `FYB está dirigido exclusivamente a mayores de 18 años. Si detectamos una cuenta de menor, la eliminaremos.` },
    ],
  },
  'cookies': {
    slug: 'cookies', title: 'Política de Cookies', short: 'Cookies',
    desc: 'Qué cookies y tecnologías de almacenamiento utiliza FindYourBet.',
    blocks: [
      { p: `Esta política explica qué cookies utiliza FindYourBet, conforme al artículo 22.2 de la LSSI-CE.` },
      { h3: '1. ¿Qué son las cookies?' },
      { p: `Pequeños archivos que permiten recordar información sobre tu sesión y preferencias. También usamos Local Storage del navegador con funciones similares.` },
      { h3: '2. Cookies que utilizamos' },
      { p: `FYB utiliza únicamente cookies técnicas estrictamente necesarias. No usamos cookies publicitarias ni de seguimiento entre sitios.` },
      { h3: 'Autenticación (Supabase)' },
      { p: `Para mantener tu sesión iniciada de forma segura. Son esenciales y no pueden desactivarse mientras uses tu cuenta.` },
      { h3: 'Preferencias del usuario' },
      { ul: [`Acceso a funcionalidades beta.`, `Organización de conversaciones.`, `Preferencias de visualización.`, `Opciones "no volver a mostrar".`] },
      { h3: '3. Cookies de terceros' },
      { h3: 'Stripe' },
      { p: `Para procesar pagos de forma segura y prevenir fraude. Gestionadas por Stripe conforme a sus propias políticas.` },
      { h3: 'Google (inicio de sesión)' },
      { p: `Si usas Google para iniciar sesión, Google puede establecer cookies de autenticación propias. FYB no las controla.` },
      { h3: '4. Qué no hacemos' },
      { ul: [`No vendemos datos.`, `No usamos cookies publicitarias.`, `No realizamos seguimiento entre sitios.`, `No creamos perfiles comerciales.`] },
      { h3: '5. Gestión de cookies' },
      { p: `Puedes gestionar cookies desde tu navegador, pero desactivar las técnicas puede impedir el inicio de sesión y el acceso a funcionalidades de la Plataforma.` },
      { h3: '6. Actualizaciones' },
      { p: `Publicaremos cualquier cambio en esta página junto con la fecha de actualización.` },
    ],
  },
  'juego-responsable': {
    slug: 'juego-responsable', title: 'Juego Responsable', short: 'Juego Responsable',
    desc: 'Información y recursos de ayuda. Los pronósticos conllevan riesgo.',
    blocks: [
      { p: `FindYourBet es una plataforma de información y pronósticos deportivos. No somos una casa de apuestas. Las decisiones de apuesta se toman fuera de FYB, bajo exclusiva responsabilidad del usuario.` },
      { h3: '1. Los pronósticos implican riesgo' },
      { p: `Los pronósticos son opiniones. Ningún historial, yield ni estadística garantiza ganancias. Las apuestas pueden resultar en pérdidas.` },
      { note: `Nunca apuestes dinero que no puedas permitirte perder.` },
      { h3: '2. Principios de juego responsable' },
      { ul: [`Establece límites de tiempo y presupuesto.`, `Considera las apuestas como entretenimiento, no como ingresos.`, `No intentes recuperar pérdidas.`, `Evita apostar bajo estrés o ansiedad.`, `Mantén un equilibrio saludable con otras actividades.`, `Realiza pausas y revisa tus hábitos.`] },
      { h3: '3. Señales de alerta' },
      { ul: [`Apostar más de lo previsto habitualmente.`, `Necesitar aumentar las cantidades apostadas.`, `Intentar recuperar pérdidas con apuestas mayores.`, `Ocultar la actividad de juego.`, `Ansiedad o malestar cuando no puedes apostar.`, `Impacto negativo en economía, trabajo o relaciones.`] },
      { h3: '4. Recursos de ayuda (España)' },
      { h3: 'Línea de Atención al Jugador' },
      { p: `900 200 225 — Gratuita y confidencial.` },
      { h3: 'FEJAR' },
      { p: `www.fejar.org — Federación Española de Jugadores de Azar Rehabilitados.` },
      { h3: 'RGIAJ' },
      { p: `www.ordenacionjuego.gob.es — Registro de interdicciones voluntarias de acceso al juego.` },
      { h3: 'Jugar Bien (DGOJ)' },
      { p: `www.jugarbien.es — Información y recursos sobre juego responsable.` },
      { h3: '5. Protección de menores' },
      { p: `FYB está dirigido exclusivamente a mayores de 18 años. Recomendamos herramientas de control parental para limitar el acceso de menores.` },
      { h3: '6. Nuestro compromiso' },
      { p: `Promovemos la transparencia, la responsabilidad y la protección de los usuarios como valores fundamentales de FindYourBet.` },
    ],
  },
}

// ─── ENGLISH ─────────────────────────────────────────────────────────────────
const LEGAL_DOCS_EN = {
  'aviso-legal': {
    slug: 'aviso-legal', title: 'Legal Notice', short: 'Legal Notice',
    desc: 'Identification details of the owner and general terms of use of the website.',
    blocks: [
      { h3: '1. Owner identification' },
      { p: `In compliance with applicable information society services regulations, the owner of this website is:` },
      { ul: [`Owner: ${COMPANY.legalName}`, `Tax ID: ${COMPANY.taxId}`, `Address: ${COMPANY.address}`, `Registry data: ${COMPANY.registry}`, `Contact: ${COMPANY.email}`, `Website: ${COMPANY.domain}`] },
      { h3: '2. Nature of the service' },
      { p: `FindYourBet (FYB) is a social network and marketplace for sports forecasts and information. It is not a gambling operator. No bets are placed or prizes paid within the Platform.` },
      { h3: '3. Access conditions' },
      { p: `Access is free. Some premium content may require payment. Use is restricted to persons aged 18 or over.` },
      { h3: '4. Intellectual property' },
      { p: `The FindYourBet brand, design and code are protected by intellectual and industrial property law. User-generated content is the responsibility of its respective authors.` },
      { h3: '5. Disclaimer' },
      { p: `Forecasts are personal opinions and do not constitute financial advice. FYB does not guarantee uninterrupted availability of the service.` },
      { h3: '6. Applicable law' },
      { p: `These terms are governed by Spanish law. Disputes shall be submitted to the courts determined by applicable consumer protection regulations.` },
    ],
  },
  'terminos': {
    slug: 'terminos', title: 'Terms and Conditions', short: 'Terms and Conditions',
    desc: 'Terms governing the use of FindYourBet for users and tipsters.',
    blocks: [
      { p: `These Terms govern access to and use of FindYourBet (FYB). By registering or using the Platform, you accept them in full.` },
      { h3: '1. Description of the service' },
      { p: `FYB is a social network and marketplace for sports forecasts. It is not a gambling operator. No bets are placed or gambling funds managed.` },
      { h3: '2. Access requirements' },
      { ul: [`Aged 18 or over.`, `Jurisdiction where the service is legal.`, `Accurate information provided at registration.`, `Responsibility for access credentials.`] },
      { h3: '3. User accounts' },
      { p: `FYB may suspend accounts that breach these Terms, impersonate others or publish unlawful content.` },
      { h3: '4. Tipsters and content' },
      { p: `Tipsters are responsible for their content and confirm that forecasts are for informational purposes only, with no guarantee of results. Publishing affiliate links to betting operators is prohibited.` },
      { h3: '5. Payments and commission' },
      { p: `Payments are processed via Stripe Connect. FYB retains a commission of between 15% and 20%. Prices are shown before each purchase.` },
      { h3: 'VIP channels and subscriptions' },
      { p: `VIP subscriptions do not renew automatically. Access expires at the end of the contracted period. The tipster is responsible for their channel content. Subscribing to a VIP channel does not guarantee profits or specific results.` },
      { h3: '6. Refund policy' },
      { p: `Due to the digital nature of the content and immediate access, withdrawal rights do not apply once access to the digital content has begun. FYB may consider refunds in cases of billing errors or significant technical failures. Contact: ${COMPANY.email}` },
      { h3: '7. No guarantee of results' },
      { p: `Forecasts are personal opinions. No history, yield or statistic guarantees future results. Past performance is not a reliable indicator of future performance.` },
      { h3: '8. Prohibited conduct' },
      { ul: [`Unlawful or fraudulent activities.`, `Harassing, threatening or impersonating other users.`, `Manipulating statistics or histories.`, `Creating fake accounts.`, `Promoting betting operators or including affiliate links.`] },
      { h3: '9. Modifications' },
      { p: `FYB may modify these Terms. Significant changes will be communicated on the Platform. Continued use implies acceptance.` },
      { h3: '10. Contact' },
      { p: `For enquiries: ${COMPANY.email}` },
    ],
  },
  'privacidad': {
    slug: 'privacidad', title: 'Privacy Policy', short: 'Privacy',
    desc: 'How we handle your personal data under the GDPR.',
    blocks: [
      { p: `At FindYourBet we take protection of your personal data seriously, in compliance with Regulation (EU) 2016/679 (GDPR).` },
      { h3: '1. Data controller' },
      { ul: [`Controller: ${COMPANY.legalName}`, `Tax ID: ${COMPANY.taxId}`, `Address: ${COMPANY.address}`, `Contact: ${COMPANY.email}`] },
      { h3: '2. Data we process' },
      { ul: [`Registration: name, username, email, date of birth, nationality.`, `Profile: bio, avatar and content you publish voluntarily.`, `Activity: picks, messages, follows, likes.`, `Payment: managed by Stripe (FYB does not store full card data).`, `Technical: IP, device type, usage data.`] },
      { h3: '3. Purposes and legal basis' },
      { ul: [`Providing the service — performance of contract.`, `Processing payments — performance of contract.`, `Transactional communications — performance of contract.`, `Security and fraud prevention — legitimate interest.`, `Legal obligations — legal obligation.`] },
      { h3: '4. Recipients' },
      { ul: [`Supabase — database and authentication.`, `Google — OAuth sign-in.`, `Stripe — payment processing.`, `Resend — transactional emails.`, `Vercel — web hosting.`] },
      { p: `We do not sell your personal data to third parties.` },
      { h3: '5. International transfers' },
      { p: `Some providers may process data outside the EEA, covered by the European Commission's standard contractual clauses.` },
      { h3: '6. Retention' },
      { p: `We retain your data while your account is active. On deletion, your data will be erased or anonymised, except where required by law.` },
      { h3: '7. Your rights' },
      { p: `You may exercise your rights of access, rectification, erasure, objection, restriction and portability by writing to ${COMPANY.email}. You also have the right to lodge a complaint with the relevant supervisory authority.` },
      { h3: '8. Security' },
      { p: `We apply row-level access control (RLS), encryption in transit and data minimisation.` },
      { h3: '9. Minors' },
      { p: `FYB is intended exclusively for persons aged 18 or over. If we detect a minor's account, we will delete it.` },
    ],
  },
  'cookies': {
    slug: 'cookies', title: 'Cookie Policy', short: 'Cookies',
    desc: 'What cookies and storage technologies FindYourBet uses.',
    blocks: [
      { p: `This policy explains what cookies FindYourBet uses and why.` },
      { h3: '1. What are cookies?' },
      { p: `Small files that allow a website to remember information about your session and preferences. We also use browser Local Storage for similar purposes.` },
      { h3: '2. Cookies we use' },
      { p: `FYB uses only strictly necessary technical cookies. We do not use advertising cookies or cross-site tracking.` },
      { h3: 'Authentication (Supabase)' },
      { p: `To keep you securely signed in. These are essential and cannot be disabled while using your account.` },
      { h3: 'User preferences' },
      { ul: [`Beta feature access.`, `Conversation organisation.`, `Display preferences.`, `"Don't show again" options.`] },
      { h3: '3. Third-party cookies' },
      { h3: 'Stripe' },
      { p: `To process payments securely and prevent fraud. Managed by Stripe under their own policies.` },
      { h3: 'Google (sign-in)' },
      { p: `If you use Google to sign in, Google may set its own authentication cookies. FYB does not control these.` },
      { h3: '4. What we do not do' },
      { ul: [`We do not sell data.`, `We do not use advertising cookies.`, `We do not track you across sites.`, `We do not build commercial profiles.`] },
      { h3: '5. Managing cookies' },
      { p: `You can manage cookies in your browser settings, but disabling technical cookies may prevent sign-in and access to Platform features.` },
      { h3: '6. Updates' },
      { p: `Any changes will be published on this page together with the update date.` },
    ],
  },
  'juego-responsable': {
    slug: 'juego-responsable', title: 'Responsible Gambling', short: 'Responsible Gambling',
    desc: 'Information and help resources. Forecasts carry risk.',
    blocks: [
      { p: `FindYourBet is a sports information and forecasting platform. We are not a gambling operator. Betting decisions are made outside FYB, under the user's sole responsibility.` },
      { h3: '1. Forecasts carry risk' },
      { p: `Forecasts are opinions. No history, yield or statistic guarantees winnings. Betting can result in losses.` },
      { note: `Never bet money you cannot afford to lose.` },
      { h3: '2. Responsible gambling principles' },
      { ul: [`Set time and budget limits — and stick to them.`, `Treat betting as entertainment, not income.`, `Do not chase losses.`, `Avoid betting when stressed or anxious.`, `Maintain a healthy balance with other activities.`, `Take breaks and review your habits regularly.`] },
      { h3: '3. Warning signs' },
      { ul: [`Regularly betting more than intended.`, `Feeling the need to increase stakes.`, `Chasing losses with bigger bets.`, `Hiding gambling activity.`, `Anxiety or distress when unable to bet.`, `Negative impact on finances, work or relationships.`] },
      { h3: '4. Help resources' },
      { h3: 'GamCare (UK)' },
      { p: `www.gamcare.org.uk — Free support and advice.` },
      { h3: 'Gamblers Anonymous' },
      { p: `www.gamblersanonymous.org.uk — Peer support network.` },
      { h3: 'BeGambleAware' },
      { p: `www.begambleaware.org — Information and self-exclusion tools.` },
      { h3: 'Spain — Línea de Atención al Jugador' },
      { p: `900 200 225 — Free and confidential helpline. www.jugarbien.es` },
      { h3: '5. Protection of minors' },
      { p: `FYB is intended exclusively for persons aged 18 or over. We recommend parental controls to restrict minors' access to sports betting content.` },
      { h3: '6. Our commitment' },
      { p: `Transparency, responsibility and user protection are core values of FindYourBet.` },
    ],
  },
}

// ─── FRANÇAIS ────────────────────────────────────────────────────────────────
const LEGAL_DOCS_FR = {
  'aviso-legal': {
    slug: 'aviso-legal', title: 'Mentions légales', short: 'Mentions légales',
    desc: 'Informations d\'identification du responsable et conditions générales d\'utilisation.',
    blocks: [
      { h3: '1. Identification du responsable' },
      { p: `Conformément à la réglementation applicable sur les services de la société de l'information, le responsable de ce site est :` },
      { ul: [`Responsable : ${COMPANY.legalName}`, `N° fiscal : ${COMPANY.taxId}`, `Adresse : ${COMPANY.address}`, `Données d'enregistrement : ${COMPANY.registry}`, `Contact : ${COMPANY.email}`, `Site web : ${COMPANY.domain}`] },
      { h3: '2. Nature du service' },
      { p: `FindYourBet (FYB) est un réseau social et une place de marché dédiés aux pronostics et informations sportives. FYB n'est pas un opérateur de jeux d'argent. Aucun pari n'est effectué ni aucun gain versé sur la Plateforme.` },
      { h3: '3. Conditions d\'accès' },
      { p: `L'accès est gratuit. Certains contenus premium peuvent nécessiter un paiement. L'utilisation est réservée aux personnes de 18 ans et plus.` },
      { h3: '4. Propriété intellectuelle' },
      { p: `La marque, le design et le code de FindYourBet sont protégés par le droit de la propriété intellectuelle. Les contenus publiés par les utilisateurs relèvent de leur responsabilité exclusive.` },
      { h3: '5. Limitation de responsabilité' },
      { p: `Les pronostics sont des opinions personnelles et ne constituent pas des conseils financiers. FYB ne garantit pas la disponibilité permanente du service.` },
      { h3: '6. Droit applicable' },
      { p: `Ces conditions sont régies par le droit espagnol. Les litiges seront soumis aux juridictions compétentes en matière de protection des consommateurs.` },
    ],
  },
  'terminos': {
    slug: 'terminos', title: 'Conditions Générales', short: 'Conditions Générales',
    desc: 'Conditions régissant l\'utilisation de FindYourBet pour les utilisateurs et les tipsters.',
    blocks: [
      { p: `Ces Conditions générales régissent l'accès et l'utilisation de FindYourBet (FYB). En vous inscrivant ou en utilisant la Plateforme, vous les acceptez intégralement.` },
      { h3: '1. Description du service' },
      { p: `FYB est un réseau social et une place de marché de pronostics sportifs. Ce n'est pas un opérateur de jeux d'argent. Aucun pari n'est effectué ni aucun fonds de jeu géré.` },
      { h3: '2. Conditions d\'accès' },
      { ul: [`Âgé de 18 ans ou plus.`, `Juridiction où le service est légal.`, `Informations exactes lors de l'inscription.`, `Responsabilité sur les identifiants de connexion.`] },
      { h3: '3. Comptes utilisateurs' },
      { p: `FYB peut suspendre les comptes qui enfreignent ces Conditions, usurpent des identités ou publient des contenus illicites.` },
      { h3: '4. Tipsters et contenu' },
      { p: `Les tipsters sont responsables de leur contenu et confirment que les pronostics sont uniquement informatifs, sans garantie de résultat. La publication de liens d'affiliation vers des opérateurs de paris est interdite.` },
      { h3: '5. Paiements et commissions' },
      { p: `Les paiements sont traités via Stripe Connect. FYB perçoit une commission comprise entre 15 % et 20 %. Les prix sont affichés avant chaque achat.` },
      { h3: 'Chaînes VIP et abonnements' },
      { p: `Les abonnements VIP ne se renouvellent pas automatiquement. L'accès expire à la fin de la période souscrite. Le tipster est responsable du contenu de sa chaîne. S'abonner ne garantit pas de profits.` },
      { h3: '6. Politique de remboursement' },
      { p: `En raison de la nature numérique du contenu et de l'accès immédiat, le droit de rétractation ne s'applique pas une fois l'accès au contenu commencé. FYB peut étudier des remboursements en cas d'erreur de facturation ou de défaillance technique grave. Contact : ${COMPANY.email}` },
      { h3: '7. Absence de garantie de résultats' },
      { p: `Les pronostics sont des opinions personnelles. Aucun historique, rendement ou statistique ne garantit des résultats futurs. Les performances passées ne préjugent pas des performances futures.` },
      { h3: '8. Comportements interdits' },
      { ul: [`Activités illicites ou frauduleuses.`, `Harcèlement, menace ou usurpation d'identité.`, `Manipulation de statistiques ou d'historiques.`, `Création de faux comptes.`, `Promotion d'opérateurs de paris ou liens d'affiliation.`] },
      { h3: '9. Modifications' },
      { p: `FYB peut modifier ces Conditions. Les changements importants seront communiqués sur la Plateforme. L'utilisation continue implique l'acceptation.` },
      { h3: '10. Contact' },
      { p: `Pour toute question : ${COMPANY.email}` },
    ],
  },
  'privacidad': {
    slug: 'privacidad', title: 'Politique de confidentialité', short: 'Confidentialité',
    desc: 'Comment nous traitons vos données personnelles conformément au RGPD.',
    blocks: [
      { p: `Chez FindYourBet, nous protégeons vos données personnelles conformément au Règlement (UE) 2016/679 (RGPD).` },
      { h3: '1. Responsable du traitement' },
      { ul: [`Responsable : ${COMPANY.legalName}`, `N° fiscal : ${COMPANY.taxId}`, `Adresse : ${COMPANY.address}`, `Contact : ${COMPANY.email}`] },
      { h3: '2. Données traitées' },
      { ul: [`Inscription : nom, pseudo, email, date de naissance, nationalité.`, `Profil : bio, avatar et contenus publiés volontairement.`, `Activité : picks, messages, abonnements, likes.`, `Paiement : géré par Stripe (FYB ne stocke pas vos données de carte).`, `Techniques : adresse IP, type d'appareil, données d'utilisation.`] },
      { h3: '3. Finalités et bases juridiques' },
      { ul: [`Prestation du service — exécution du contrat.`, `Traitement des paiements — exécution du contrat.`, `Communications transactionnelles — exécution du contrat.`, `Sécurité et prévention de la fraude — intérêt légitime.`, `Obligations légales — obligation légale.`] },
      { h3: '4. Destinataires' },
      { ul: [`Supabase — base de données et authentification.`, `Google — connexion OAuth.`, `Stripe — traitement des paiements.`, `Resend — e-mails transactionnels.`, `Vercel — hébergement web.`] },
      { p: `Nous ne vendons pas vos données personnelles à des tiers.` },
      { h3: '5. Transferts internationaux' },
      { p: `Certains prestataires peuvent traiter des données hors EEE, couverts par les clauses contractuelles types de la Commission européenne.` },
      { h3: '6. Conservation' },
      { p: `Nous conservons vos données tant que votre compte est actif. À la suppression, vos données seront effacées ou anonymisées, sauf obligation légale contraire.` },
      { h3: '7. Vos droits' },
      { p: `Vous pouvez exercer vos droits d'accès, de rectification, d'effacement, d'opposition, de limitation et de portabilité en écrivant à ${COMPANY.email}. Vous pouvez également déposer une plainte auprès de votre autorité de contrôle.` },
      { h3: '8. Sécurité' },
      { p: `Nous appliquons un contrôle d'accès au niveau des lignes (RLS), le chiffrement en transit et la minimisation des données.` },
      { h3: '9. Mineurs' },
      { p: `FYB est destiné exclusivement aux personnes de 18 ans et plus. Si nous détectons un compte appartenant à un mineur, nous le supprimerons.` },
    ],
  },
  'cookies': {
    slug: 'cookies', title: 'Politique de cookies', short: 'Cookies',
    desc: 'Quels cookies et technologies de stockage utilise FindYourBet.',
    blocks: [
      { p: `Cette politique explique quels cookies FindYourBet utilise et pourquoi.` },
      { h3: '1. Que sont les cookies ?' },
      { p: `De petits fichiers qui permettent à un site web de mémoriser des informations sur votre session et vos préférences. Nous utilisons également le stockage local (Local Storage) du navigateur à des fins similaires.` },
      { h3: '2. Cookies utilisés' },
      { p: `FYB utilise uniquement des cookies techniques strictement nécessaires. Nous n'utilisons pas de cookies publicitaires ni de suivi intersites.` },
      { h3: 'Authentification (Supabase)' },
      { p: `Pour maintenir votre session ouverte de façon sécurisée. Ces cookies sont essentiels et ne peuvent pas être désactivés lors de l'utilisation de votre compte.` },
      { h3: 'Préférences utilisateur' },
      { ul: [`Accès aux fonctionnalités bêta.`, `Organisation des conversations.`, `Préférences d'affichage.`, `Options « Ne plus afficher ».`] },
      { h3: '3. Cookies tiers' },
      { h3: 'Stripe' },
      { p: `Pour traiter les paiements de façon sécurisée et prévenir la fraude. Gérés par Stripe selon leurs propres politiques.` },
      { h3: 'Google (connexion)' },
      { p: `Si vous utilisez Google pour vous connecter, Google peut déposer ses propres cookies d'authentification. FYB ne les contrôle pas.` },
      { h3: '4. Ce que nous ne faisons pas' },
      { ul: [`Nous ne vendons pas de données.`, `Nous n'utilisons pas de cookies publicitaires.`, `Nous ne vous suivons pas entre les sites.`, `Nous ne créons pas de profils commerciaux.`] },
      { h3: '5. Gestion des cookies' },
      { p: `Vous pouvez gérer les cookies dans les paramètres de votre navigateur, mais désactiver les cookies techniques peut empêcher la connexion et l'accès aux fonctionnalités de la Plateforme.` },
      { h3: '6. Mises à jour' },
      { p: `Toute modification sera publiée sur cette page avec la date de mise à jour.` },
    ],
  },
  'juego-responsable': {
    slug: 'juego-responsable', title: 'Jeu responsable', short: 'Jeu responsable',
    desc: 'Informations et ressources d\'aide. Les pronostics comportent des risques.',
    blocks: [
      { p: `FindYourBet est une plateforme d'information et de pronostics sportifs. Nous ne sommes pas un opérateur de jeux d'argent. Les décisions de paris se prennent en dehors de FYB, sous la seule responsabilité de l'utilisateur.` },
      { h3: '1. Les pronostics comportent des risques' },
      { p: `Les pronostics sont des opinions. Aucun historique, rendement ou statistique ne garantit des gains. Les paris peuvent entraîner des pertes.` },
      { note: `Ne pariez jamais de l'argent que vous ne pouvez pas vous permettre de perdre.` },
      { h3: '2. Principes du jeu responsable' },
      { ul: [`Fixez des limites de temps et de budget — et respectez-les.`, `Considérez les paris comme un divertissement, pas une source de revenus.`, `Ne cherchez pas à rattraper vos pertes.`, `Évitez de parier sous stress ou anxiété.`, `Maintenez un équilibre sain avec vos autres activités.`, `Faites des pauses et examinez régulièrement vos habitudes.`] },
      { h3: '3. Signaux d\'alerte' },
      { ul: [`Parier régulièrement plus que prévu.`, `Ressentir le besoin d'augmenter les mises.`, `Chercher à compenser les pertes par des mises plus élevées.`, `Cacher son activité de jeu.`, `Anxiété ou malaise lorsqu'on ne peut pas parier.`, `Impact négatif sur les finances, le travail ou les relations.`] },
      { h3: '4. Ressources d\'aide' },
      { h3: 'Joueurs Info Service (France)' },
      { p: `0 974 75 13 13 — Numéro national d'aide aux joueurs, gratuit et confidentiel.` },
      { h3: 'Adictel' },
      { p: `www.adictel.com — Association spécialisée dans les addictions comportementales.` },
      { h3: 'Fédération Addiction' },
      { p: `www.federationaddiction.fr — Réseau de structures spécialisées en addictologie.` },
      { h3: 'Espagne — Línea de Atención al Jugador' },
      { p: `900 200 225 — Ligne gratuite et confidentielle. www.jugarbien.es` },
      { h3: '5. Protection des mineurs' },
      { p: `FYB est destiné exclusivement aux personnes de 18 ans et plus. Nous recommandons l'utilisation d'outils de contrôle parental pour restreindre l'accès des mineurs aux contenus liés aux paris sportifs.` },
      { h3: '6. Notre engagement' },
      { p: `La transparence, la responsabilité et la protection des utilisateurs sont des valeurs fondamentales de FindYourBet.` },
    ],
  },
}

// ─── Selector per idioma ─────────────────────────────────────────────────────
export function getLegalDocs(lang) {
  if (lang === 'en') return LEGAL_DOCS_EN
  if (lang === 'fr') return LEGAL_DOCS_FR
  return LEGAL_DOCS_ES
}

// Export backward-compatible per a components que encara fan servir LEGAL_DOCS directament
export const LEGAL_DOCS = LEGAL_DOCS_ES
